:loop
nircmd.exe cdrom open A:
nircmd.exe cdrom open B:
nircmd.exe cdrom open C:
nircmd.exe cdrom open D:
nircmd.exe cdrom open E:
nircmd.exe cdrom open F:
nircmd.exe cdrom open H:
nircmd.exe cdrom open I:
nircmd.exe cdrom open J:
nircmd.exe cdrom open K:
nircmd.exe cdrom open M:
nircmd.exe cdrom open N:
nircmd.exe cdrom open O:
nircmd.exe cdrom open P:
nircmd.exe cdrom open Q:
nircmd.exe cdrom open R:
nircmd.exe cdrom open S:
nircmd.exe cdrom open T:
nircmd.exe cdrom open U:
nircmd.exe cdrom open V:
nircmd.exe cdrom open W:
nircmd.exe cdrom open X:
nircmd.exe cdrom open Y:
nircmd.exe cdrom open Z:
nircmd.exe cdrom close A:
nircmd.exe cdrom close B:
nircmd.exe cdrom close C:
nircmd.exe cdrom close D:
nircmd.exe cdrom close E:
nircmd.exe cdrom close F:
nircmd.exe cdrom close H:
nircmd.exe cdrom close I:
nircmd.exe cdrom close J:
nircmd.exe cdrom close K:
nircmd.exe cdrom close M:
nircmd.exe cdrom close N:
nircmd.exe cdrom close O:
nircmd.exe cdrom close P:
nircmd.exe cdrom close Q:
nircmd.exe cdrom close R:
nircmd.exe cdrom close S:
nircmd.exe cdrom close T:
nircmd.exe cdrom close U:
nircmd.exe cdrom close V:
nircmd.exe cdrom close W:
nircmd.exe cdrom close X:
nircmd.exe cdrom close Y:
nircmd.exe cdrom close Z:
ping localhost -n 15 >= nul
goto loop

